apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-server
  labels:
    app: mqtt-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-server
  template:
    metadata:
      labels:
        app: mqtt-server
    spec:
      containers:
        - name: mqtt-server
          image: rrdr20/srv
          imagePullPolicy: Never
          ports:
            - containerPort: 1883

