apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-subscriber
  labels:
    app: mqtt-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-subscriber
  template:
    metadata:
      labels:
        app: mqtt-subscriber
    spec:
      containers:
        - name: mqtt-subscriber
          image: rrdr20/subscriber
          imagePullPolicy: Never

